SELECT DISTINCT ?g ?domain ?attribute ?range (COUNT(?s) as ?numberOfConnections) WHERE {
  GRAPH ?g {
    ?s
      a
        ?domain;
      ?attribute
        ?o.
    {
      ?o
        a
          ?range.
    }
    UNION
    {
      ?s
        ?attribute
          ?o.
      BIND(datatype(?o) as ?range)
    }
    FILTER(bound(?range))
  }
FILTER(?g NOT IN (<http://www.openlinksw.com/schemas/virtrdf#>, <http://www.w3.org/2002/07/owl#>, <http://localhost:8890/sparql>, <http://mu.semte.ch/graphs/system/jobs>))
}
GROUP BY ?g ?domain ?attribute ?range
ORDER BY ?domain ?attribute ?range
