PREFIX org: <http://www.w3.org/ns/org#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX schema: <http://schema.org/>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX euro: <http://data.europa.eu/m8g/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX persoon: <https://data.vlaanderen.be/ns/persoon#>
PREFIX adres: <https://data.vlaanderen.be/ns/adres#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX lblodlg: <https://data.lblod.info/vocabularies/leidinggevenden/>
PREFIX dc_terms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX euvoc: <http://publications.europa.eu/ontology/euvoc#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX ch: <http://data.lblod.info/vocabularies/contacthub/>    
PREFIX code: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT DISTINCT * WHERE {
  ?bestuur
    a
      ?type.
  OPTIONAL {
    ?bestuur
      skos:prefLabel
        ?label
  }
  OPTIONAL {
  	?bestuur
    	ere:typeEredienst
     		?typeEredienstUri.
    OPTIONAL {
    	?typeEredienstUri
       	skos:prefLabel
        	?typeEredienst.
	  }
  }
  OPTIONAL {
    ?bestuur
      org:hasPrimarySite
        ?primarySite.
	  OPTIONAL {    
      ?primarySite
        organisatie:bestaatUit
          ?sa.
		  OPTIONAL {
        ?sa
          locn:adminUnitL2
            ?provincie.
      }
    }
  }

  FILTER (?type IN (
    <http://data.lblod.info/vocabularies/erediensten/CentraalBestuurVanDeEredienst>,
    <http://data.lblod.info/vocabularies/erediensten/BestuurVanDeEredienst>
  ))

  ?bestuur
    adms:identifier
      ?identifier_sharepoint_id.
  ?identifier_sharepoint_id
    skos:notation
      "SharePoint identificator".
  ?identifier_sharepoint_id
    generiek:gestructureerdeIdentificator
      ?id_structured_sharepoint_id.
  ?id_structured_sharepoint_id
    generiek:lokaleIdentificator
      ?sharepoint_id_nr.
  ?bestuur2
    adms:identifier
      ?identifier_sharepoint_id2.
  ?identifier_sharepoint_id2
    skos:notation
      "SharePoint identificator".
  ?identifier_sharepoint_id2
    generiek:gestructureerdeIdentificator
      ?id_structured_sharepoint_id2.
  ?id_structured_sharepoint_id2
    generiek:lokaleIdentificator
      ?sharepoint_id_nr2.
  
  FILTER (
    ?sharepoint_id_nr = ?sharepoint_id_nr2 &&
    ?bestuur != ?bestuur2
  )

  OPTIONAL {
    ?bestuur2
      skos:prefLabel
        ?label2
  }
  OPTIONAL {
  	?bestuur2
    	ere:typeEredienst
     		?typeEredienstUri2.
    OPTIONAL {
    	?typeEredienstUri2
       	skos:prefLabel
        	?typeEredienst2.
	  }
  }
  OPTIONAL {
    ?bestuur2
      org:hasPrimarySite
        ?primarySite2.
	  OPTIONAL {    
      ?primarySite2
        organisatie:bestaatUit
          ?sa2.
		  OPTIONAL {
        ?sa2
          locn:adminUnitL2
            ?provincie2.
        }
      }
    }
}